apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-an8q
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-an8q
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-an8q
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-an8q
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-an8q
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vdhw-tenant/rhtap-demo-app/hacbs-test-project-an8q@sha256:e54b3b26521d79ff49cc84bc1c16e83ad769ff11a37a0e35d2a1f16973534cb9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
